changelog:
  categories:
    - title: Breaking changes
      labels:
        - release:major
    - title: New features
      labels:
        - release:minor
        - enhancement
        - feature
    - title: Fixes
      labels:
        - release:patch
        - bug
        - fix
    - title: Other changes
      labels:
        - "*"
  exclude:
    labels:
      - skip-changelog
